//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 10:04:49 AM SGT 
//


package com.mcbf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mcbf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mcbf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.ADDRESSES }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.ADDRESSES createREQUESTMESSAGEENTITIESENTITYADDRESSES() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.ADDRESSES();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.SERVICES }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.SERVICES createREQUESTMESSAGEENTITIESENTITYSERVICES() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.SERVICES();
    }

    /**
     * Create an instance of {@link REQUEST }
     * 
     */
    public REQUEST createREQUEST() {
        return new REQUEST();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.PRODUCTS.PRODUCT }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.PRODUCTS.PRODUCT createREQUESTMESSAGEENTITIESENTITYPRODUCTSPRODUCT() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.PRODUCTS.PRODUCT();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.IDS }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.IDS createREQUESTMESSAGEENTITIESENTITYIDS() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.IDS();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES createREQUESTMESSAGEENTITIES() {
        return new REQUEST.MESSAGE.ENTITIES();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.SERVICES.SERVICE }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.SERVICES.SERVICE createREQUESTMESSAGEENTITIESENTITYSERVICESSERVICE() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.SERVICES.SERVICE();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.CONTACTS }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.CONTACTS createREQUESTMESSAGEENTITIESENTITYCONTACTS() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.CONTACTS();
    }

    /**
     * Create an instance of {@link REQUEST.HEADER }
     * 
     */
    public REQUEST.HEADER createREQUESTHEADER() {
        return new REQUEST.HEADER();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.ADDRESSES.ADDRESS }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.ADDRESSES.ADDRESS createREQUESTMESSAGEENTITIESENTITYADDRESSESADDRESS() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.ADDRESSES.ADDRESS();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.NAMES.NAME }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.NAMES.NAME createREQUESTMESSAGEENTITIESENTITYNAMESNAME() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.NAMES.NAME();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.IDS.ID }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.IDS.ID createREQUESTMESSAGEENTITIESENTITYIDSID() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.IDS.ID();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE }
     * 
     */
    public REQUEST.MESSAGE createREQUESTMESSAGE() {
        return new REQUEST.MESSAGE();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.CONTACTS.CONTACT }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.CONTACTS.CONTACT createREQUESTMESSAGEENTITIESENTITYCONTACTSCONTACT() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.CONTACTS.CONTACT();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.PRODUCTS }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.PRODUCTS createREQUESTMESSAGEENTITIESENTITYPRODUCTS() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.PRODUCTS();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY createREQUESTMESSAGEENTITIESENTITY() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY();
    }

    /**
     * Create an instance of {@link REQUEST.MESSAGE.ENTITIES.ENTITY.NAMES }
     * 
     */
    public REQUEST.MESSAGE.ENTITIES.ENTITY.NAMES createREQUESTMESSAGEENTITIESENTITYNAMES() {
        return new REQUEST.MESSAGE.ENTITIES.ENTITY.NAMES();
    }

}
