--<ScriptOptions statementTerminator=";"/>

ALTER TABLE prdimgm0 DROP PRIMARY KEY;

ALTER TABLE prdimgm0 DROP INDEX Img_Category;

ALTER TABLE prdimgm0 DROP INDEX Img_Category;

ALTER TABLE prdimgm0 DROP INDEX Img_Name;

ALTER TABLE prdimgm0 DROP INDEX Img_Name;

DROP TABLE prdimgm0;

CREATE TABLE prdimgm0 (
	IMGPRDID INT NOT NULL,
	IMGPRDTITLE VARCHAR(45) NOT NULL,
	IMGPRDIMG LONGBLOB NOT NULL,
	IMGSIZE INT DEFAULT 0 NOT NULL,
	IMGCTGY VARCHAR(25) NOT NULL,
	IMGNAME VARCHAR(50) NOT NULL,
	IMGDATID INT NOT NULL,
	IMGVERSION INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (IMGDATID,IMGPRDID)
) ENGINE=MyISAM;

CREATE INDEX Img_Category ON prdimgm0 (IMGCTGY ASC);

CREATE INDEX Img_Category ON prdimgm0 (IMGDATID ASC);

CREATE INDEX Img_Name ON prdimgm0 (IMGDATID ASC);

CREATE INDEX Img_Name ON prdimgm0 (IMGNAME ASC);

ALTER TABLE prdimgm0 ADD PRIMARY KEY (IMGDATID, IMGPRDID);

